# Generated by Django 3.0.8 on 2020-08-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('summary', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('author', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField()),
            ],
        ),
    ]
