# Generated by Django 3.0.8 on 2020-08-08 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200807_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='fid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
